name: kathir_final
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  supabase: ^2.5.6
  supabase_flutter: ^2.5.6
  go_router: ^14.2.0
  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  file_picker: ^8.1.2
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.4
  google_fonts: ^6.2.1
  intl: ^0.20.2
  image_picker: ^1.0.7
  uuid: ^4.3.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  google_generative_ai: ^0.4.6
  http: ^1.1.0
  qr_flutter: ^4.1.0
  flutter_rating_bar: ^4.0.1
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  dartz: ^0.10.0
  flutter_bloc: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - lib/resources/assets/images/
    - .env
