name: kathir_final
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  supabase: ^2.5.6
  supabase_flutter: ^2.5.6
  go_router: ^14.2.0
  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  dartz: ^0.10.0
  flutter_bloc: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - lib/resources/assets/images/
